context:
  name: py-crude-resource-monitor
  version: "0.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/I-Al-Istannen/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 11898e73fd1654a293d8670bb4d57e127ab803b0185fee076fab355d959f7e62
  patches:
    - if: win
      then: 0001-pnpm-bat.patch

build:
  number: 1

requirements:
  build:
    - pnpm
    - pnpm-licenses
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then:
        - libunwind

tests:
  - script:
      - py-crude-resource-monitor --help

about:
  homepage: https://github.com/I-Al-Istannen/${{ name }}
  summary: A memory and cpu utilization monitor that correlates the data with Python stacktraces. Supports multiprocessing.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - THIRDPARTY-frontend.yml

extra:
  recipe-maintainers:
    - pavelzw
